from django.db import models
from django.contrib.auth.models import User

class Entry(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=50)
  image = models.ImageField(upload_to='images/',blank=True)
  monday_start_time_1 = models.TimeField(null=True,blank=True)
  monday_end_time_1 = models.TimeField(null=True,blank=True)
  tuesday_start_time_1 = models.TimeField(null=True,blank=True)
  tuesday_end_time_1 = models.TimeField(null=True,blank=True)
  wednesday_start_time_1 = models.TimeField(null=True,blank=True)
  wednesday_end_time_1 = models.TimeField(null=True,blank=True)
  thursday_start_time_1 = models.TimeField(null=True,blank=True)
  thursday_end_time_1 = models.TimeField(null=True,blank=True)
  friday_start_time_1 = models.TimeField(null=True,blank=True)
  friday_end_time_1 = models.TimeField(null=True,blank=True)
  saturday_start_time_1 = models.TimeField(null=True,blank=True)
  saturday_end_time_1 = models.TimeField(null=True,blank=True)
  sunday_start_time_1 = models.TimeField(null=True,blank=True)
  sunday_end_time_1 = models.TimeField(null=True,blank=True)
  monday_start_time_2 = models.TimeField(null=True,blank=True)
  monday_end_time_2 = models.TimeField(null=True,blank=True)
  tuesday_start_time_2 = models.TimeField(null=True,blank=True)
  tuesday_end_time_2 = models.TimeField(null=True,blank=True)
  wednesday_start_time_2 = models.TimeField(null=True,blank=True)
  wednesday_end_time_2 = models.TimeField(null=True,blank=True)
  thursday_start_time_2 = models.TimeField(null=True,blank=True)
  thursday_end_time_2 = models.TimeField(null=True,blank=True)
  friday_start_time_2 = models.TimeField(null=True,blank=True)
  friday_end_time_2 = models.TimeField(null=True,blank=True)
  saturday_start_time_2 = models.TimeField(null=True,blank=True)
  saturday_end_time_2 = models.TimeField(null=True,blank=True)
  sunday_start_time_2 = models.TimeField(null=True,blank=True)
  sunday_end_time_2 = models.TimeField(null=True,blank=True)
  description = models.TextField(null=True,blank=True)
  menu = models.TextField(null=True,blank=True)
  address = models.CharField(max_length=120,null=True,blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return self.title