# Generated by Django 3.0.3 on 2020-02-13 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0004_entry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='monday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 551397), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 551581), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 551550), null=True),
        ),
    ]
