# Generated by Django 3.0.3 on 2020-02-13 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0006_auto_20200213_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='friday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641817), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='friday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642281), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='friday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641788), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='friday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642253), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='monday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641581), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='monday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641990), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='monday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641535), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='monday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641961), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='saturday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641875), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='saturday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642338), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='saturday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641846), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='saturday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642309), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sunday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641932), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sunday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642395), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sunday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641903), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sunday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642366), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641760), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642224), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641732), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thursday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642194), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tuesday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641643), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tuesday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642049), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tuesday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641612), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tuesday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642019), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wednesday_end_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641703), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wednesday_end_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642107), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wednesday_start_time_1',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 641673), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wednesday_start_time_2',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 642077), null=True),
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.time(0, 0, 0, 643412), null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='EndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.time(0, 0, 0, 643757), null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.Entry')),
            ],
        ),
    ]
