# Generated by Django 3.0.3 on 2020-02-13 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0010_auto_20200213_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='friday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='friday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='friday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='friday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='monday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='monday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='monday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='monday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='saturday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='saturday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='saturday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='saturday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sunday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sunday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sunday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sunday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thursday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thursday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thursday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thursday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tuesday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tuesday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tuesday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tuesday_start_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='wednesday_end_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='wednesday_end_time_2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='wednesday_start_time_1',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='wednesday_start_time_2',
        ),
        migrations.AddField(
            model_name='endtime',
            name='day',
            field=models.CharField(default='MON', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starttime',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=10),
        ),
        migrations.AlterField(
            model_name='endtime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 798002), null=True),
        ),
        migrations.AlterField(
            model_name='starttime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 797526), null=True),
        ),
    ]
