# Generated by Django 3.0.3 on 2020-02-13 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0015_auto_20200213_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='endtime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 703471), null=True),
        ),
        migrations.AlterField(
            model_name='starttime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 702997), null=True),
        ),
    ]
