# Generated by Django 3.0.3 on 2020-02-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0018_auto_20200213_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AlterField(
            model_name='endtime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 233584), null=True),
        ),
        migrations.AlterField(
            model_name='starttime',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0, 0, 233122), null=True),
        ),
    ]
